---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    author: hbc
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis-pod
    author: hbc
...